# Generated by Django 4.2.7 on 2024-12-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_accommodation_center'),
        ('properties', '0003_alter_localizeaccommodation_unique_together_and_more'),
    ]

    operations = [
    ]
