# Generated by Django 4.2.7 on 2024-12-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_merge_20241203_1034'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='localizeaccommodation',
            name='unique_property_language',
        ),
        migrations.AlterUniqueTogether(
            name='localizeaccommodation',
            unique_together={('property', 'language')},
        ),
    ]
